# TCL File Generated by Component Editor 15.0
# Wed Aug 08 16:37:02 BRT 2018
# DO NOT MODIFY


# 
# sobel_op "sobel_op" v1.0
#  2018.08.08.16:37:02
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module sobel_op
# 
set_module_property DESCRIPTION ""
set_module_property NAME sobel_op
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sobel_op
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sobel_op
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sobel_op.v VERILOG PATH ../Guiga/UEFEY/6_semestre_sd/MI_SD/P3/quartus/source/sobel_op.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter threshold STD_LOGIC_VECTOR 32
set_parameter_property threshold DEFAULT_VALUE 32
set_parameter_property threshold DISPLAY_NAME threshold
set_parameter_property threshold TYPE STD_LOGIC_VECTOR
set_parameter_property threshold UNITS None
set_parameter_property threshold ALLOWED_RANGES 0:1023
set_parameter_property threshold HDL_PARAMETER true


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave dataa dataa Input 32
add_interface_port nios_custom_instruction_slave datab datab Input 32
add_interface_port nios_custom_instruction_slave result result Output 32

